# Generated by Django 4.2.3 on 2023-07-06 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='featured',
        ),
    ]
