# Generated by Django 4.2.3 on 2023-07-11 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0003_order_orderitem_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='featured',
            field=models.BooleanField(db_index=True, default=0),
        ),
    ]
